language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - hhvm
    - php: 7.0

before_script:
  # install dependencies to add repos
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  # install oracle jdk 8
  - sudo apt-get install -y oracle-java8-installer
  - sudo update-alternatives --auto java
  - sudo update-alternatives --auto javac
  - export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
  # install Neo4j
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - sed -i.bak '/\(dbms\.security\.auth_enabled=\).*/s/^#//g' "neo4j-community-$NEO4J_VERSION/conf/neo4j.conf"
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  - sleep 3 # give neo4j some time to start

  # install composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

env:
  - NEO4J_VERSION="3.0.4"
  - JAVA_HOME="/usr/lib/jvm/java-8-oracle"
  - JRE_HOME="/usr/lib/jvm/java-8-oracle"

notifications:
  slack:
    rooms:
      - vinelab:52MiVOHdct34FRg2o9sPBlJJ#graphdb
